name: example
description: Present clean and professional documentation with Swagger + shelf.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  shelf: ">=1.3.1 <2.0.0"
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_swagger_ui:
    path: ..
  


