name: shelf_swagger_ui
description: Present clean and professional documentation with Swagger + shelf.
version: 0.0.1
repository: https://github.com/Flutterando/shelf_swagger_ui

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  shelf: ">=1.3.1 <2.0.0"
  yaml: ">=3.1.1 <4.0.0"


