get:
  tags:
  - "project"
  summary: "get all project"
  responses:
    "200":
      description: "successful operation"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../swagger.yaml#/components/schemas/ProjectEntity"
